syntax = "proto3";

// Java-пакет для сгенерированных классов
option java_package = "org.example.kickstarter.grpc";

// Все сгенерированные классы будут в отдельных файлах (не во вложенных классах)
option java_multiple_files = true;

// Пакет proto (для именования в других .proto файлах при импорте)
package projectanalytics;

// Сервисы
// Unary RPC - один запрос это один ответ (типа аналог REST GET/POST)
service ProjectAnalytics {
  rpc AnalyzeProject (AnalyzeProjectRequest) returns (ProjectAnalysisResponse);
}

// Сообщения
// В proto3 все поля опциональны по умолчанию (zero-value = не задано).
// Номера полей (1, 2, 3...) используются в бинарном формате —
// они не должны меняться после релиза
// чтобы не нарушить совместимость

// Запрос: то, что мост будет отправлять в калькулятор
message AnalyzeProjectRequest {
  int64 project_id = 1;
  double goal = 2;
  int32 days_active = 3;
  int32 description_length = 4;
}

// Ответ: то, что калькулятор вернет обратно
message ProjectAnalysisResponse {
  int64 project_id = 1;
  double success_probability = 2; // Шанс успеха в % (например, 85.5)
  string hype_level = 3;          // "LOW", "MEDIUM", "HIGH"
  int32 estimated_backers = 4;    // Примерное число нужных спонсоров
}