version: '3.8'

services:
  kickstarter-rabbitmq:
    image: rabbitmq:4.0-management
    container_name: kickstarter-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - kickstarter-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  kickstarter-api:
    build:
      context: .
      dockerfile: Dockerfile.rest  # <-- Указываем на наш новый файл
    container_name: kickstarter-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_RABBITMQ_HOST=kickstarter-rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    depends_on:
      kickstarter-rabbitmq:
        condition: service_healthy
    networks:
      - kickstarter-network
    restart: unless-stopped

  kickstarter-audit:
    build:
      context: .
      dockerfile: Dockerfile.audit # <-- Указываем на файл аудита
    container_name: kickstarter-audit-app
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_RABBITMQ_HOST=kickstarter-rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    depends_on:
      kickstarter-rabbitmq:
        condition: service_healthy
    networks:
      - kickstarter-network
    restart: unless-stopped

networks:
  kickstarter-network:
    driver: bridge

volumes:
  rabbitmq_data: